spring:

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
      url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      data-locations: classpath*:db/h2/data.sql

server:
  servlet:
    encoding:
      force-response: true

